exclude: ^(blib2to3/|profiling/|tests/data/)
repos:
  - repo: local
    hooks:
      - id: regex
        name: regex
        language: system
        entry: regex
        require_serial: true
        types: [python]
