language: python
python:
  - 3.6
install:
  - pip install -r requirements-dev.txt
script:
  - pytest
  - py.test --cov-report=xml --cov=pre_commit_hooks tests/

after_script:
- bash <(curl -s https://codecov.io/bash)
